---
name: BEAM Coverdata to JSON
description: Easily convert BEAM coverdata into a JSON object
branding:
  icon: 'download-cloud'
  color: 'gray-dark'
inputs:
  input:
    description: Input coverdata location
    default: _site/cover
  otp-version:
    description: OTP Version
    default: 26
  output:
    description: coverage JSON filename
    default: _site/cover/coverage.json
runs:
  using: composite
  steps:
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{inputs.otp-version}}
    - run: |
        make -C $GITHUB_ACTION_PATH app
      shell: bash
    - run: |
        $GITHUB_ACTION_PATH/cover2json --input ${{inputs.input}} --output ${{inputs.output}}
      shell: bash
